### ISSUE TITLE
Friday Meeting

### ISSUE THREAD

**Issue by bradreeder** [saferTogether/saferTogether#13]
* get feedback on user research
* will this be a smart phone app or on desktop?
* what information should be on the landing page? (privacy disclaimer, information about saferTogether or the purpose of the survey?)
* what information should be on the results page? (links to relevant organisations, risk assessment, a contact form?)
* should the website be styled and coloured similarly to the [saferTogether](http://safertogether.org.uk/) website?

**Comment by Nicky-Cummings** [comment]
Thanks Bradley, emailed everyone just now and asked for feedback here..

**Comment by shigufta-khan** [comment]
- our research on phones used by service user is majority use smart phones. so that seems to be the better option especially as it will make it more accessible. 
- would be good to have safer together colours and the logo on the landing page with contact numbers, maybe a drop down menu on the side that has the privacy disclaimer links to the RIC, safety plan and information etc 
- results page I think should safety advice and information on local services. tab to press to send the information automatically to the nearest service.

**Comment by Nicky-Cummings** [comment]
Fab! Thanks Shigufta that's great..

**Comment by Nicky-Cummings** [comment]
Just spoke to Debbie for a catch up and agree with above fro Shigufta. Definitely app rather than on Safer Together website but ability to download the app from the site.

Plaease can everyone attach to this hub any of the following documents.. Confidentiality agreement, RIC, Safety Planning resources.

Lets discuss how we get the referrals into services directly in our call this Friday and then I can confirm al of the individual service info. Bradley do you have a Safer Together leaflet detailing this?

**Comment by Nicky-Cummings** [comment]
Just come off the cal with Bradley and Shophia.

We discussed the focus and key objectives of this design sprint and in summary we are producing the app for use on smart phones with users being able to access safety advice and resources, obtain contact info for Safer Together support services and to be able to complete the RIC.

At this stage in the development, data will not be automatically sent to services unless the user has completed a short contact form and asked for further info/support.

When the app is opened the landing page will have navigation to complete the RIC, access safety resources, complete a contact form and hold the contact info for each service. On completing the RIC users will be presented with 'what to do next' type info and info about the MARAC etc.

Does this all sound ok with you?

I need a copy of the RIC, safety resources, and a good quality image of the Safer Together logo (png file). Please attach these.

Jen, I'll call you Monday before my next call with Bradley on Monday at 10am.

Many thanks :) 

Please can everyone let me now that they are receiving this info as I'm not sure who is in the group..

**Comment by shigufta-khan** [comment]
Hi Nicky

I think it sounds good as long as the victim gets an understanding of the risk they are in, get some safety advice and contact number to access support we have covered the essentials. As long as its not complicated and easy to follow should be okay.



Shigufta



[cid:image002.png@01CF9C2D.898D6480]Shigufta Khan | Chief Executive Officer
Blackburn & Darwen District
Without Abuse
43 King Street, Blackburn, BB2 2DH
Tel: 01254 260465

[cid:image005.png@01CF99C5.2F71FC00]Web: www.bddwa.org.uk<http://www.bddwa.org.uk/>
Email: shigufta.khan@bddwa.org.uk<mailto:shigufta.khan@bddwa.org.uk>


Supported by Comic Relief, Henry Smith and Children In Need. BDDWA is a registered charity and exists to assist in the relief of people who have suffered or who are at risk of suffering domestic abuse, through the provision of support, advice and accommodation.

[safer together logo (2)][cid:image001.png@01CF6197.DA126BB0][cid:image004.png@01CF6198.067B2250]

Registered company 5834929 Registered charity 1116444.

**Comment by Nicky-Cummings** [comment]
![Uploading safer together logo.jpg…]()

The flyer is too big to upload from here so I'll email over Bradley..
